### ISSUE TITLE
name of the library book used for your design?

### ISSUE THREAD

**Issue by xedover** [74hc595/Ultim809#3]
You said you "found a microcomputer design book at the library that uses the 6809 in its examples." Can you tell us the name of the book?

**Comment by cbmeeks** [comment]
+1

**Comment by 74hc595** [comment]
Oh boy. I can't remember the name, but it was already out of print when I checked it out. I recall it was the first edition of the book; later editions used the 68000. It wasn't a large book; maybe half an inch thick.

I think my only lead might be to find my old Santa Clara County Library card, log into their website, and  see if it's in my checkout history.

**Comment by phiber1** [comment]
Now that I have your attention, there's a crucial error in your schematic
in the graphics logic section. I opened an issue about it a few years ago.

-Mark

**Comment by 74hc595** [comment]
@phiber1 Thank you for the reminder, I just replied to your issue.

**Comment by 74hc595** [comment]
**This is it!** _Microprocessor System Design Fundamentals_ by Kenneth J. Breeding: https://www.amazon.com/Microprocessor-System-Fundamentals-Kenneth-Breeding/dp/0135642795

ISBN: 9780135642795
