### ISSUE TITLE
Using your code

### ISSUE THREAD

**Issue by jblang** [74hc595/Ultim809#4]
Since your license says to let you know about my use of your code, and I don't use twitter, I'm letting you know here.  I've ported your plasma code to Z80 as a demo program for the TMS9918A board I designed for the RC2014.

Code is here: https://github.com/jblang/TMS9918A/blob/master/examples/plasma.asm

I am also working on porting over Conway's Game of Life, and will have it in the same repository.

**Comment by 74hc595** [comment]
Thanks! That's awesome!
